name: Android Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.1.1413
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - name: Install dependencies
        run: flutter pub get

      - name: Compile ClojureDart
        run: clojure -M:cljd compile

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Application
        uses: actions/upload-artifact@v4
        with:
          name: cljd_datomworld-android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
